config/routes.rb
Rails.application.routes.draw do
  get 'admin/index' => 'admin#index'
  
  controller :sessions do
      
      get 'login' => :new
      post 'login' => :create
      delete 'logout' => :destroy
      
  end
      
    
  resources :users
  resources :orders
  resources :line_items
  resources :line_items
  resources :carts
  get 'store/index'

  resources :products do
      get :who_bought, on: :member
  end

  root 'store#index', as: 'store'

end

app/models/cart.rb
class Cart < ActiveRecord::Base
    has_many :line_items, dependent: :destroy
    def add_product(product_id)
        current_item = line_items.find_by(product_id: product_id)
        if current_item
            current_item.quantity += 1
        else
          current_item = line_items.build(product_id: product_id)
        end
        current_item
    end
    
    def quantity_change(product_id)
        current_item = line_items.find_by(product_id: product_id)
        current_item += quantity
        return current_item
    end
    
    def total_price
        line_items.to_a.sum { |item| item.total_price }
    end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  skip_before_action :authorize, only: [ :show, :create, :edit, :update, :destroy]
  include CurrentCart
  before_action :set_cart, only: [:show, :edit, :update, :destroy]
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart
  before_action :cart_access, only: [:show, :edit, :update, :destroy]
  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy if @cart.id == session[:cart_id]
    session[:cart_id] = nil
    respond_to do |format|
      format.html { redirect_to store_url, notice: 'Your cart is currently empty' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params.fetch(:cart, {})
    end
    
    def invalid_cart
        logger.error "Attempt to acces invalid cart #{params[:id]}"
        redirect_to store_url, notice: "Invalid Cart"
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Carts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<div class="wrapper col-vs-12">
<h2 style="text-align: center; padding-bottom: 25px;"> Your Shoping Cart </h2>
 <!-- <table>
	<% @cart.line_items.each do |item| %>
 	  <tr>
		<td><%= item.quantity %>&times; </td>
 		<td><%= item.product.title %></td>
 		<td class="item_price"><%= number_to_currency(item.total_price) %></td>
 	  </tr>
	<% end %>
	
 	<tr class="total_line">
 		<td colspan="2">Total</td>
 		<td class="total_cell"><%= number_to_currency(@cart.total_price) %></td>
 	</tr>
 </table>

<%= link_to 'Edit', edit_cart_path(@cart) %> |
<%= link_to 'Back', carts_path %> 
<%= button_to "Empty Cart", @cart, method: :delete,
  data: { confirm: "Are you sure?" } %> -->
  
  
<div class="container">
	<table id="cart" class="table table-hover table-condensed">
	  <% @cart.line_items.each do |item| %>
    				<thead>
						<tr>
							<th style="width:45%">Product</th>
							<th style="width:10%">Price</th>
							<th style="width:20%" class="text-center">Quantity</th>
							<th style="width:15%" class="text-center">Subtotal</th>
							<th style="width:10%"></th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td data-th="Product">
								<div class="row">
									<div class="col-sm-2 hidden-xs"><img src="<%= item.product.picture.url %> "alt="..." class="img-responsive"/></div>
									<div class="col-sm-10">
										<h4 class="nomargin"><%= item.product.title %></h4>
										<p><%= item.product.description %></p>
									</div>
								</div>
							</td>
							<td data-th="Price" style="vertical-align: middle;"><%= number_to_currency(item.product.price) %></td>
							<td data-th="Quantity" style="vertical-align: middle;" class="Form">
								<!--<input type="number" class="form-control text-center" value= <%= item.quantity %> > -->
							
								<%= simple_form_for(item, html: { class: "form-horizontal myForm text-center" }) do |f| %>
								
								    <%= f.number_field :quantity, class: "form-control" %>
									 
									<%= button_tag(type: "submit", class: "btn btn-info btn-sm refresh" )  do %>
								      <i class="fa fa-refresh"></i>
							   
								    <% end %>
									 
								<% end %>
							
							</td>
							
							
							<td data-th="Subtotal" class="text-center Subtotal" style="vertical-align: middle;"><%= number_to_currency(item.total_price) %> </td>
							<td class="actions text-center" data-th="" style="vertical-align: middle;">
								<!-- <button class="btn btn-info btn-sm"><i class="fa fa-refresh"></i></button> -->
							<%= simple_form_for(item, :html => { method: :delete }) do |f| %>
								
								<%= button_tag(type: "submit", class: "btn btn-danger btn-sm") do %> 
								  <i class="fa fa-trash-o"></i>
								<% end %>
							<% end %>
								
													
							</td>
						</tr>
					</tbody>
	 <% end %>
					<tfoot>
						<tr class="visible-xs">
							<td class="text-center"><strong>Total: <%= number_to_currency(@cart.total_price) %></strong></td>
						</tr>
						<tr>
							<td> <%= link_to store_path, class:"btn btn-warning" do %>
							  		<i class="fa fa-angle-left"></i> Continue Shopping
							  	 <% end %> 
							  	 </td>
							<td colspan="2" class="hidden-xs"></td>
							<td class="hidden-xs text-center" style="vertical-align: middle;"><strong>Total: <%= number_to_currency(@cart.total_price) %></strong></td>
							<td><%= link_to raw("Checkout <i class=\"fa fa-angle-right\"></i>"), 
          							new_order_path, 
          							method: :get,
         							 class: "btn btn-success btn-block" %>
							</td> 
						</tr>
					</tfoot>
				</table>
</div>


<%= button_to "Empty Cart", @cart, method: :delete, class: "btn btn-danger", style: "margin: 0 auto; display: block; margin-bottom: 20px;",
  data: { confirm: "Are you sure?" } %>

</div>
<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">


<!--
<script> 
  $(document).ready(function () {
   $('.form-horizontal').each( function () {
     ('.refresh').click(function() {
      alert("hi")
      });
    });
});
</script> 

<script>
$(document).ready(function() {
  $('.myForm').each(function() {
    $(this).attr('id', function(i) {
      return 'myForm'+(i+1);
    var hello = "hello";
    $('.id').append('<p>  hello </p>');
    });
  });
});
</script> 
  
<script> 
$(document).ready(function() {
  $('.row').each(function() {
    $(this).uniqueId();
    });
}); 

$(function() {
   $('.myForm').each(function() {
      var thisId = this.id;
      $(this).append('<span>' + thisId + '</span>');
      $('.refresh').attr('id', 'hot');
      var ID = $('.refresh').id;
      
      $('.refresh').append('<span>' + "hello" + '</span>');
      
      });
    });
</script> -->