config/routes.rb
Rails.application.routes.draw do
  get 'admin/index' => 'admin#index'
  
  controller :sessions do
      
      get 'login' => :new
      post 'login' => :create
      delete 'logout' => :destroy
      
  end
      
    
  resources :users
  resources :orders
  resources :line_items
  resources :line_items
  resources :carts
  get 'store/index'

  resources :products do
      get :who_bought, on: :member
  end

  root 'store#index', as: 'store'

end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <div class="alert text-center <%= alert_class_for(type) %> fade in">
    <%= message %>
  </div>
<% end %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tux</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta charset="utf-8">
  <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
</head>
<body>

  <%= render partial: 'layouts/flash_messages', flash: flash %>	
  <div id="side">
  <% if session[:user_id] %>
  <div class="btn-group buttons">
    <ul> 
      <li><%= link_to "Orders", orders_path %></li>
      <li><%= link_to "Products", products_path %></li>
      <li><%= link_to "Users", users_path %></li>
      <li><%= link_to "Store", store_path %></li>
    </ul>
  </div>
    <%= button_to "Logout", logout_path, method: :delete %>
  <% end %>
  </div>

<%= yield %>

</body>
</html>